#!/bin/bash
echo $C3"Setting up cfg.pub"$C0
cd $(dirname $0)
git config credential.helper store
[ -e ~/clone-me ] || cp clone-me ~
cd
[ -d utils ] || git clone https://github.com/ciax/utils.git
. ~/utils/setup
